/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Principal.Inicio;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jacky
 */
public class Reporteria extends javax.swing.JFrame {

    /**
     * Creates new form Reporteria
     */
    public Reporteria() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LblImages = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BtnTopViajes = new javax.swing.JMenuItem();
        BtnClientes = new javax.swing.JMenuItem();
        BtnConductores = new javax.swing.JMenuItem();
        BtnVehiculos = new javax.swing.JMenuItem();
        BtnMejorRuta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        BtnClientesR = new javax.swing.JMenuItem();
        BtnConducR = new javax.swing.JMenuItem();
        BtnVehiculosR = new javax.swing.JMenuItem();
        BtnRutasR = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        BtnEDD = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        BtnReturn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reportes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 120, -1));

        jScrollPane2.setViewportView(LblImages);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 970, 580));

        jMenu1.setText("Tops");

        BtnTopViajes.setText("Top Viajes");
        jMenu1.add(BtnTopViajes);

        BtnClientes.setText("Top Clientes");
        jMenu1.add(BtnClientes);

        BtnConductores.setText("Top Conductores");
        BtnConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConductoresActionPerformed(evt);
            }
        });
        jMenu1.add(BtnConductores);

        BtnVehiculos.setText("Top Vehiculos");
        jMenu1.add(BtnVehiculos);

        BtnMejorRuta.setText("Mejor Ruta");
        BtnMejorRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMejorRutaActionPerformed(evt);
            }
        });
        jMenu1.add(BtnMejorRuta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Estructuras");

        BtnClientesR.setText("Clientes");
        BtnClientesR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClientesRActionPerformed(evt);
            }
        });
        jMenu2.add(BtnClientesR);

        BtnConducR.setText("Conductores");
        BtnConducR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConducRActionPerformed(evt);
            }
        });
        jMenu2.add(BtnConducR);

        BtnVehiculosR.setText("Vehiculos");
        BtnVehiculosR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVehiculosRActionPerformed(evt);
            }
        });
        jMenu2.add(BtnVehiculosR);

        BtnRutasR.setText("Rutas");
        BtnRutasR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRutasRActionPerformed(evt);
            }
        });
        jMenu2.add(BtnRutasR);

        jMenuItem1.setText("BlockChain");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        BtnEDD.setText("Estructura Completa");
        BtnEDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEDDActionPerformed(evt);
            }
        });
        jMenu2.add(BtnEDD);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Regresar");

        BtnReturn.setText("Regresar");
        BtnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturnActionPerformed(evt);
            }
        });
        jMenu3.add(BtnReturn);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConductoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConductoresActionPerformed

    private void BtnVehiculosRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVehiculosRActionPerformed
        try {
            ImageIcon ims;
            Inicio.arbolito.imprimirNodo();
            Thread.sleep(500);
            ims = new ImageIcon("bTree.jpg");
            ims.getImage().flush();
            ims = new ImageIcon("bTree.jpg");
            LblImages.setIcon(ims);
            LblImages.revalidate();
            LblImages.repaint(); // TODO add your handling code here:
        } catch (Exception ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_BtnVehiculosRActionPerformed

    private void BtnClientesRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClientesRActionPerformed
        try {
            ImageIcon ims;
            Inicio.tablita.graficar();
            Thread.sleep(500);
            ims = new ImageIcon("Hash.jpg");
            ims.getImage().flush();
            ims = new ImageIcon("Hash.jpg");
            LblImages.setIcon(ims);
            LblImages.revalidate();
            LblImages.repaint(); // TODO add your handling code here:
        } catch (Exception ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_BtnClientesRActionPerformed

    private void BtnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturnActionPerformed
        MenuP principal = new MenuP();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnReturnActionPerformed

    private void BtnConducRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConducRActionPerformed

        try {
            ImageIcon ims;
            Inicio.lcd.ReporteLCD();
            Thread.sleep(500);
            ims = new ImageIcon("ReporteConductores.png");
            ims.getImage().flush();
            ims = new ImageIcon("ReporteConductores.png");
            LblImages.setIcon(ims);
            LblImages.revalidate();
            LblImages.repaint(); // TODO add your handling code here:
        } catch (Exception ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_BtnConducRActionPerformed

    private void BtnRutasRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRutasRActionPerformed
        try {
            ImageIcon ims;
            Inicio.graph.Graficar();
            Thread.sleep(500);
            ims = new ImageIcon("ReporteRutas.png");
            ims.getImage().flush();
            ims = new ImageIcon("ReporteRutas.png");
            LblImages.setIcon(ims);
            LblImages.revalidate();
            LblImages.repaint(); // TODO add your handling code here:
        } catch (Exception ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_BtnRutasRActionPerformed

    private void BtnEDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEDDActionPerformed

        try {
            ImageIcon ims;
            Inicio.cadenaBloques.GraficarRG();
            Thread.sleep(500);
            ims = new ImageIcon("ReporteGeneral.jpg");
            ims.getImage().flush();
            ims = new ImageIcon("ReporteGeneral.jpg");
            LblImages.setIcon(ims);
            LblImages.revalidate();
            LblImages.repaint(); // TODO add your handling code here:

            File miDir = new File("ReporteGeneral.jpg");
            Desktop.getDesktop().open(miDir);
        } catch (Exception ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_BtnEDDActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        /* */
 /*BLOCKCHAIN*/
        try {
            ImageIcon ims;
            Inicio.cadenaBloques.ReporteBC();
            Thread.sleep(500);
            ims = new ImageIcon("ReporteBC.png");
            ims.getImage().flush();
            ims = new ImageIcon("ReporteBC.png");
            LblImages.setIcon(ims);
            LblImages.revalidate();
            LblImages.repaint(); // TODO add your handling code here:
        } catch (Exception ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BtnMejorRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMejorRutaActionPerformed
        String llave = JOptionPane.showInputDialog("Ingrese Llave de viaje", JOptionPane.QUESTION_MESSAGE);

        try {

            ImageIcon ims;
            Inicio.cadenaBloques.MejorRuta(llave);
            Thread.sleep(500);
            ims = new ImageIcon("ReporteMejorRuta.png");
            ims.getImage().flush();
            ims = new ImageIcon("ReporteMejorRuta.png");
            LblImages.setIcon(ims);
            LblImages.revalidate();
            LblImages.repaint(); // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(Reporteria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnMejorRutaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnClientes;
    private javax.swing.JMenuItem BtnClientesR;
    private javax.swing.JMenuItem BtnConducR;
    private javax.swing.JMenuItem BtnConductores;
    private javax.swing.JMenuItem BtnEDD;
    private javax.swing.JMenuItem BtnMejorRuta;
    private javax.swing.JMenuItem BtnReturn;
    private javax.swing.JMenuItem BtnRutasR;
    private javax.swing.JMenuItem BtnTopViajes;
    private javax.swing.JMenuItem BtnVehiculos;
    private javax.swing.JMenuItem BtnVehiculosR;
    private javax.swing.JLabel LblImages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
